In [1]:
%load_ext autoreload
%autoreload 2
import argparse
import os
import commentjson as json

import numpy as np

import shutil
import time
import sys

pyngp_path = '/home/koala/AgriSim-virtual-NeRF-training/models/instant-ngp/build'
sys.path.append(pyngp_path)
import pyngp as ngp # noqa
sys.path.append('/home/koala/AgriSim-virtual-NeRF-training/models/instant-ngp/')
from common import *
from scenes import *

from tqdm import tqdm

ImportError: /home/koala/anaconda3/envs/asim/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /home/koala/AgriSim-virtual-NeRF-training/models/instant-ngp/build/pyngp.cpython-38-x86_64-linux-gnu.so)

In [1]:
import numpy as np

In [2]:
selec_poses = np.array([[1,1,1],[2,2,2]])
poses = np.array([[1,1,1],[2,2,2],[3,3,3],[4,4,4]])

In [8]:
np.where(poses == selec_poses[0])

(array([0, 0, 0]), array([0, 1, 2]))

In [11]:
poses.tolist().index(selec_poses[1].tolist())

1

In [15]:

import argparse
import os
import time
import sys
import commentjson as json
import numpy as np

sys.path.append("..")
from AgriSim.unity_sampler.sampler import UnitySampler

sampler = UnitySampler(object_family='02843684', 
                                object_id='1b73f96cf598ef492cba66dc6aeabcd4', 
                                screenshot_dir="../data/unity_images",
                                config_path='../AgriSim/config.yaml')

In [18]:
sampler.generate_imgs(sample_default=True, default_sample_num=50, 
                      additional_viewpoints=[[0, 5, 0, 3.14, 0]])

Generated 50 default unity images.


In [37]:
ap = [7,20, 7]
theta, phi = cartesian_to_spherical(*ap)
*ap, theta, phi

(7, 20, 7, 0.7853981633974483, 0.4596193309638148)

In [28]:

import numpy as np
import quaternion as q
import math
def cartesian_to_spherical(x, z, y):
    phi = math.atan2(math.sqrt(x ** 2 + y ** 2), z)
    theta = math.atan2(y, x) if x >= 0 else math.atan2(y, x) + math.pi
    return theta, phi


In [49]:
start_pose = np.array([0, 0, 1])  # x, y, z
end_pose = np.array([1, 0, 1])

end_pose = end_pose/np.linalg.norm(end_pose)
q_xyz = np.cross(start_pose, end_pose)
q_w = np.dot(start_pose, end_pose)
q_xyz, q_w

(array([0.        , 0.70710678, 0.        ]), 0.7071067811865475)

In [19]:
from scipy.spatial.transform import Rotation

# Create a rotation object from Euler angles specifying axes of rotation
rot = Rotation.from_euler('xyz', [90, 45, 30], degrees=True)

# Convert to quaternions and print
rot_quat = rot.as_quat()
print(rot_quat)

[ 0.56098553  0.43045933 -0.09229596  0.70105738]


In [ ]:
    def _get_viewing_dir(self, theta, phi): 
        """
        Convert the camera poses into position/quaternion data to feed into Unity
    
        Args:
            theta (float): polar angle
            phi (float): azimuth angle
        Returns:
            R (np.ndarray): 3x3 Rotation matrix
        """
        # Viewing direction needs to point inwards, so flip the signs of the angle
        theta, phi = -theta, -phi
        R = np.array([
            [np.sin(theta)*np.cos(phi), np.cos(theta)*np.cos(phi), -np.sin(phi)],
            [np.sin(theta)*np.sin(phi), np.cos(theta)*np.sin(phi), np.cos(phi)],
            [np.cos(theta), -np.sin(theta), 0],
        ])
        
        return R

In [55]:
limit = 20
random_poses = (np.random.random_sample((100, 3))-0.5)*limit*2
random_poses[:, 1] = -np.abs(random_poses[:, 1])
random_poses

array([[ 11.2070421 ,  -3.96662105,  -1.76990945],
       [ -9.8816518 , -10.51264564,   4.41553482],
       [  5.86170078,  -7.18211757, -18.07820419],
       [  9.32318508,  -6.64157771,   5.28852729],
       [ -8.39933002,  -0.95194761,   1.49766416],
       [  3.97589021,  -8.45097282, -17.69031965],
       [-12.3238359 , -12.30566337, -16.63239012],
       [ 14.29001858, -14.49214561,   5.13430707],
       [ -2.17694909, -16.85678187,  12.48784132],
       [ -1.7729561 , -12.43796973,  17.5187516 ],
       [ 10.38162423, -11.74929498,  17.48393181],
       [ 17.91619016,  -1.95041387,   1.38427127],
       [ 11.72087716,  -1.46618376,   2.51269721],
       [ 13.58743001, -16.98923163,  13.06189205],
       [ -1.13297388,  -9.5220754 ,   7.78980461],
       [-13.60957178, -15.01001884,  -1.61823011],
       [-16.16216371,  -2.4273482 ,   0.96544906],
       [-11.207968  ,  -6.87515196,  -0.50541337],
       [ 11.97696151,  -3.06122404, -17.28842456],
       [ 16.60322788, -11.22529